# Generated by Django 5.1.3 on 2024-11-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
