# Generated by Django 5.1.3 on 2024-12-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_request_options_request_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='patronymic',
        ),
    ]
