# Generated by Django 5.1.3 on 2024-12-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_privacypolicy_privacypolicyparagraph'),
        ('projects', '0010_project_estimates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Фото в галерее', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.category', verbose_name='Категория'),
        ),
    ]
