# Generated by Django 5.1.3 on 2024-12-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_galleryphoto_options_galleryphoto_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
    ]
