# Generated by Django 5.1.3 on 2024-12-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_delete_galleryphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='contacts/certificates', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото сертификата',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
