# Generated by Django 5.1.3 on 2024-12-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_certificatephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='title',
        ),
    ]
