# Generated by Django 5.1.3 on 2024-12-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_remove_privacypolicy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contacts/certificates', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
