# Generated by Django 5.1.3 on 2025-01-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_request_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
    ]
