# Generated by Django 5.1.3 on 2025-01-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_rename_first_name_worker_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contacts/certificates', verbose_name='Фото')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.DeleteModel(
            name='PartnerImage',
        ),
    ]
