# Generated by Django 5.1.3 on 2025-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Сообщение'),
        ),
    ]
