# Generated by Django 5.1.3 on 2024-11-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='project',
        ),
        migrations.RemoveField(
            model_name='material',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rooftype',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_projects', to='projects.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material_projects', to='projects.material', verbose_name='Материал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='roof_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roof_type_projects', to='projects.material', verbose_name='Тип кровли'),
            preserve_default=False,
        ),
    ]
