# Generated by Django 5.1.3 on 2024-11-24 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='roof_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_type_projects', to='projects.rooftype', verbose_name='Тип кровли'),
        ),
    ]
