# Generated by Django 5.1.3 on 2024-11-25 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_roof_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphoto',
            options={'verbose_name': 'Фото проекта', 'verbose_name_plural': 'Фото проекта'},
        ),
    ]
