# Generated by Django 5.1.3 on 2024-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectphoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bedrooms_quantity',
            field=models.SmallIntegerField(default=1, verbose_name='Количество спален'),
        ),
    ]
