# Generated by Django 5.1.3 on 2024-12-09 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_bedrooms_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bathrooms_quantity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='project',
            name='floors_quantity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rooms_quantity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество комнат'),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
