# Generated by Django 5.1.3 on 2024-12-09 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_bathrooms_quantity_project_floors_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bathrooms_quantity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество санузлов'),
        ),
    ]
