# Generated by Django 5.1.3 on 2024-12-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_bathrooms_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimates',
            field=models.FileField(blank=True, null=True, upload_to='projects/estimates', verbose_name='Смета'),
        ),
    ]
