# Generated by Django 5.1.3 on 2024-12-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_gallery_photo_project_is_in_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_in_gallery',
            field=models.BooleanField(default=False, verbose_name='Отображается в галерее'),
        ),
    ]
