# Generated by Django 5.1.3 on 2025-01-17 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_project_rooms_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_projects', to='projects.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='project',
            name='roof_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roof_type_projects', to='projects.rooftype', verbose_name='Тип кровли'),
        ),
    ]
