# Generated by Django 5.1.3 on 2025-01-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
    ]
