# Generated by Django 5.1.3 on 2025-01-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bathrooms_quantity',
            field=models.SmallIntegerField(default=1, verbose_name='Количество санузлов'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floors_quantity',
            field=models.SmallIntegerField(default=1, verbose_name='Количество этажей'),
        ),
    ]
