# Generated by Django 5.1.3 on 2025-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_bathrooms_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laoyouts', verbose_name='Изображение')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('size', models.CharField(max_length=120, verbose_name='Габариты')),
                ('ceiling_height', models.CharField(max_length=120, verbose_name='Высота потолков')),
                ('seasonality', models.CharField(max_length=120, verbose_name='Сезонность')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
            },
        ),
    ]
