# Generated by Django 5.1.3 on 2025-02-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='project',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='projects.project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
