# Generated by Django 5.1.3 on 2025-02-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_layout_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
