# Generated by Django 5.1.3 on 2025-02-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_layout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=500, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
