version: '3.8'

services:
  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: your_password
    command: redis-server --requirepass $REDIS_PASSWORD
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '../../etc/ssl:/etc/ssl'
      - './static:/var/www/static' 
      - './media:/media' 
    depends_on:
      - backend 
      - redis
    networks:
      - dev

  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "5555:5555"
    volumes:
      - './db:/db'
      - ./static:/var/www/static
      - ./media:/media
      - ./amocrm_tokens:/amocrm_tokens
    networks:
      - dev
    depends_on:
      - redis

networks:
  dev: