# Generated by Django 5.1.3 on 2024-12-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
