# Generated by Django 5.1.3 on 2024-11-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwoGISReview',
            new_name='Review',
        ),
    ]
