# Generated by Django 5.1.3 on 2024-12-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviewphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='username',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='Имя автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='author_avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Аватар автора'),
        ),
    ]
