# Generated by Django 5.1.3 on 2024-12-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.review', verbose_name='Отзыв'),
        ),
    ]
