# Generated by Django 5.1.3 on 2024-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_platform_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icon',
            field=models.FileField(null=True, upload_to='reviews/platforms', verbose_name='Иконка'),
        ),
    ]
