# Generated by Django 5.1.3 on 2024-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_platform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='average_rating',
            field=models.FloatField(default=4.9, verbose_name='Средний рейтинг компании на платформе'),
        ),
    ]
