# Generated by Django 5.1.3 on 2024-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_videoreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='url',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
    ]
