# Generated by Django 5.1.3 on 2024-12-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_videoreview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoreview',
            name='preview_url',
            field=models.URLField(default='', verbose_name='Ссылка на превью'),
            preserve_default=False,
        ),
    ]
