# Generated by Django 5.1.3 on 2024-12-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_videoreview_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='url',
            field=models.URLField(default='', verbose_name='Ссылка на профиль компании'),
            preserve_default=False,
        ),
    ]
