# Generated by Django 5.1.3 on 2024-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_platform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icon',
            field=models.ImageField(null=True, upload_to='reviews/platforms', verbose_name='Иконка'),
        ),
    ]
