# Generated by Django 5.1.3 on 2025-01-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_platform_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoReview',
        ),
    ]
