# Generated by Django 5.1.3 on 2024-12-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slide_bathrooms_quantity_slide_bedrooms_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='button_text',
        ),
    ]
