# Generated by Django 5.1.3 on 2024-12-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_slide_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='', max_length=120, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(default='', verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission',
            field=models.TextField(default='', verbose_name='Миссия компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка на Whatsapp'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_mode',
            field=models.TextField(default='', verbose_name='Режим работы'),
        ),
    ]
