# Generated by Django 5.1.3 on 2024-12-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_companyinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Миссия компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Whatsapp'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='working_mode',
            field=models.TextField(blank=True, null=True, verbose_name='Режим работы'),
        ),
    ]
