# Generated by Django 5.1.3 on 2024-12-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_companyinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Полное название организации'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='inn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
    ]
