# Generated by Django 5.1.3 on 2024-12-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_companyinfo_two_gis_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
