# Generated by Django 5.1.3 on 2024-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='subheader',
            field=models.TextField(default='', max_length=200, verbose_name='Подзаголовок'),
        ),
    ]
