# Generated by Django 5.1.3 on 2024-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_companyinfo_subheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfact',
            name='company_info',
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='company_info',
        ),
        migrations.AddField(
            model_name='cooperationstage',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyAdvantage',
        ),
        migrations.DeleteModel(
            name='CompanyFact',
        ),
        migrations.DeleteModel(
            name='CompanyService',
        ),
    ]
