# Generated by Django 5.1.3 on 2024-12-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cooperationstage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationstage',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
