# Generated by Django 5.1.3 on 2024-12-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_cooperationstage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationstage',
            name='number',
            field=models.CharField(max_length=2, verbose_name='Порядковый номер'),
        ),
    ]
