# Generated by Django 5.1.3 on 2024-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_cooperationstage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationstage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cooperationstage',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Название'),
        ),
    ]
