# Generated by Django 5.1.3 on 2024-12-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_cooperationstage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularquestion',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
    ]
