# Generated by Django 5.1.3 on 2024-12-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_popularquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationstage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
