# Generated by Django 5.1.3 on 2024-12-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_cooperationstage_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperationstage',
            old_name='icon',
            new_name='image',
        ),
    ]
