# Generated by Django 5.1.3 on 2024-12-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_icon_cooperationstage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationstage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/cooperation_stages', verbose_name='Картинка'),
        ),
    ]
