# Generated by Django 5.1.3 on 2025-02-04 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_cooperationstage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='bathrooms_quantity',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Количество санузлов'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='bedrooms_quantity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='square',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Площадь'),
        ),
    ]
